#!/bin/sh
#
# setup
#
# Author: Márcio Pessoa <marcio.pessoa@gmail.com>
# Contributors: none
#
# Description:
#   Install or upgrade xC software.
#
# Example:
#   setup install
#   setup update
#
# Change log:
# 2019-01-01
#         * Changed: Python 3 ready.
#
# 2018-06-13
#         * Added: Python compilation before install or update installation.
#
# 2018-05-10
#         * Fixed: Some user output messages.
#         * Changed: Default output of some commands was suppressed.
#
# 2017-06-14
#         * Added: Python-termcolor python-sh as system dependencies.
#         * Added: TrueType font configuration.
#         * Added: Configuration to /usr/share/xsessions/xc.desktop file.
#         * Added: Auto login configuration to file
#                  /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
#
# 2016-05-28
#         * Scrash version.
#

readonly ACTION=$1
readonly OPTION=$2
readonly PYTHON="python3"

if [ "$OPTION" = "--verbose" ]; then
  verbose="--verbose"
else
  verbose=""
fi

message() {
  message=$1
  echo "$message""... \\c"
}

check_return() {
  return=$1
  if [ "$return" -eq 0 ]; then
    echo "Done."
  else
    echo "Fail."
    exit 1
  fi
}

install() {
  # Dependencies
  message "Installing software dependencies"
  apt update >/dev/null 2>&1 && \
    apt -y install \
      python3-pip \
      >/dev/null 2>&1
  check_return $?
  message "Installing Python 3 dependencies"
  pip3 install pygame termcolor
  check_return $?
  # Copy files
  message "Creating directory structure"
  mkdir -p /opt/sciemon/xc
  check_return $?
  message "Setting user permissions"
  chown --recursive "$USER". /opt/sciemon
  check_return $?
  update
  # Fonts
  mkdir -p ~/.fonts
  ln -s /opt/sciemon/xc/fonts/Digirtu_.ttf ~/.fonts >/dev/null 2>&1
  # Configuration file
  #message "Configuration file"
  ln -s /opt/sciemon/xc/xC.json "$HOME"/.xC.json >/dev/null 2>&1
  #check_return $?
  #check_return $?
  #
  # sh -c 'cat > /usr/share/xsessions/xc.desktop'
# [Desktop Entry]
# Type=Application
# Exec=/opt/sciemon/xc/xc
# Name=xC
# Comment=Axes Controller

  #
  # sh -c 'cat >> /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf'
# autologin-user=srackham"
}

update() {
  message "Compiling"
  find . -name "*.py" -exec "$PYTHON" -m py_compile {} \;
  check_return $?
  message "Copying files"
  rsync --include-from .rsync_include.txt \
        --exclude-from .rsync_exclude.txt \
        $verbose --delete --archive ./ \
        /opt/sciemon/xc
  check_return $?
}

case "$ACTION" in
  'install')
    install
    ;;
  'update')
    update
    ;;
  *)
    echo "Usage:
setup install
setup update
"
    exit 1
    ;;
esac
exit 0
