#!/bin/sh
#
# setup
# 
# Author: Márcio Pessoa <marcio.pessoa@sciemon.com>
# Contributors: none
# 
# Description:
#   Install or upgrade xC software on device.
# 
# Example: 
#   setup install /opt/sciemon/xc
#   setup install user@computer:/opt/sciemon/xc
#   setup update /opt/sciemon/xc
#   setup update user@computer:/opt/sciemon/xc
# 
# Change log:
# 2017-06-14
#         * Improvement: Added python-termcolor python-sh as system
#                        dependencies.
#         * New feature: Added TrueType font configuration.
#         * Improvement: Added configuration to /usr/share/xsessions/xc.desktop
#                        file.
#         * New feature: Added auto login configuration to file 
#                        /usr/share/lightdm/lightdm.conf.d/\
#                        60-lightdm-gtk-greeter.conf
# 
# 2016-05-28
#         * Scrash version.
#

readonly ACTION=$1
readonly DESTINATION=$2

message() {
  message=$1
  echo "$message""... \c"
}

check_return() {
  return=$1
  if [ "$return" -eq 0 ]; then
    echo "Done."
  else
    echo "Fail."
    exit 1
  fi
}

install() {
  # Dependencies
  message "Installing software dependencies"
  apt-get -y install \
    python-serial \
    python-pygame \
    python-termcolor \
    python-sh \
    python-psutil
  check_return $?
  # Copy files
  mkdir -p /opt/sciemon/xc
  check_return $?
  chown "$USER". /opt/sciemon/xc
  check_return $?
  update
  # Fonts
  mkdir ~/.fonts
  ln -s /opt/sciemon/xc/fonts/Digirtu_.ttf ~/.fonts
  # Configuration file
  message "Copying configuration file"
  ln -s /opt/sciemon/xc/devices.json "$HOME"/.devices.json
  # check_return $?
  #
  # sh -c 'cat > /usr/share/xsessions/xc.desktop'
# [Desktop Entry]
# Type=Application
# Exec=/opt/sciemon/xc/xc
# Name=xC
# Comment=Axes Controller

  #
  # sh -c 'cat >> /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf'
# autologin-user=srackham"
}

update() {
  message "Copying files"
  rsync --include-from rsync_include.txt \
        --exclude-from rsync_exclude.txt \
        --verbose --delete --archive ./ \
        /opt/sciemon/xc
  check_return $?
}

case "$ACTION" in
  'install')
    install
    ;;
  'update')
    update
    ;;
  *)
    echo "Usage:
setup install
setup update
"
    exit 1
    ;;
esac
exit 0
