---
- name: Install/update xC
  hosts: all
  vars:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    dest: /opt
    path: xc

  tasks:
    - name: APT - Install dependencies on Ubuntu
      become: true
      apt:
        package: [
          python3-pygame,
          python3-termcolor,
          python3-psutil,
          python3-serial
        ]
        state: present
        cache_valid_time: 3600
        update_cache: yes
      tags: apt

    - name: APT - Install dependencies on Raspberry Pi 3
      become: true
      apt:
        package: [
          python3-rpi.gpio,
          rpi.gpio-common
        ]
        state: present
        cache_valid_time: 3600
        update_cache:
      when:
        - ansible_facts['architecture'] == "armv7l"
      tags: raspberry

    - name: APT - Install dependencies on Raspberry Pi 3+
      become: true
      apt:
        package: [
          python3-rpi.gpio,
          rpi.gpio-common
        ]
        state: present
        cache_valid_time: 3600
        update_cache:
      when:
        - ansible_facts['architecture'] == "aarch64"
      tags: raspberry

    - name: Filesystem - Create work directory if it does not exist
      become: true
      file:
        path: "{{ dest }}/{{ path }}"
        state: directory
        mode: '0755'
        owner: "{{ owner }}"
        group: "{{ group }}"
      tags: filesystem

    - name: Install - Copy files
      synchronize:
        src: .
        dest: "{{ dest }}"
        delete: yes
        dirs: yes
      tags: copy

    - name: Fonts - Create fonts directory if it does not exist
      file:
        path: ~/.fonts
        state: directory
        mode: '0755'
      tags: fonts

    - name: Fonts - Link fonts if it does not exist
      file:
        src: /opt/xc/fonts/Digirtu_.ttf
        dest: ~/.fonts/Digirtu_.ttf
        state: link
      tags: fonts

    - name: Environment - Configure ~/.profile
      lineinfile:
        path: ~/.profile
        line: . {{ dest }}/{{ path }}/.profile
      tags: environment

    - name: Configuration - Create config file
      file:
        src: "{{ dest }}/{{ path }}/xC.json"
        dest: ~/.xC.json
        state: link
      tags: configuration
